# Generated by Django 4.2.24 on 2025-09-22 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.AddField(
            model_name='franchise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
