# Generated by Django 4.2.24 on 2025-09-22 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0002_rename_account_number_franchise_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='FranchiseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='franchise_qr/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='paysecure.franchise')),
            ],
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='franchise_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paysecure.franchiseaccount'),
        ),
    ]
