# Generated by Django 4.2.24 on 2025-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
