# Generated by Django 4.2.24 on 2025-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0007_rename_utr_number_withdrawalrequest_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='accepted_by_franchise',
            field=models.BooleanField(default=False),
        ),
    ]
