# Generated by Django 4.2.22 on 2025-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0008_withdrawalrequest_accepted_by_franchise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='utr_number',
            new_name='franchise_utr',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='franchise_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='user_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='user_utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
