# Generated by Django 4.2.22 on 2025-10-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysecure', '0011_franchisebank_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinrequest',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='payinrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
